import React from 'react';
import Navigation from '@/components/Navigation/Navigation';

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navigation />
      {children}
    </>
  );
}
